apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: audit-collector-apiserver-reader-binding
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: audit-collector
  namespace: guardian-system
roleRef:
  kind: Role
  name: audit-collector-apiserver-reader
  apiGroup: rbac.authorization.k8s.io