apiVersion: v1
kind: Service
metadata:
  name: guardian-collector-service
  namespace: guardian-system
spec:
  selector:
    app: guardian-collector
  ports:
    - protocol: TCP
      port: 8000
      nodePort: 30007
  type: NodePort